package io.github.mudrichenkoevgeny.backend.feature.user.config.envkeys

/**
 * Environment variable names used to configure the user feature.
 *
 * Values are read by the default configuration factory (`UserConfigFactoryImpl`) using an env reader
 * and secret files where applicable.
 */
object UserEnvKeys {
    const val JWT_SECRET_FILE = "JWT_SECRET_FILE"
    const val ACCESS_TOKEN_EXPIRATION_SECONDS = "ACCESS_TOKEN_EXPIRATION_SECONDS"
    const val REFRESH_TOKEN_EXPIRATION_SECONDS = "REFRESH_TOKEN_EXPIRATION_SECONDS"
    const val ADMIN_ACCOUNTS_JSON_SECRET_FILE = "ADMIN_ACCOUNTS_JSON_SECRET_FILE"
    const val AVAILABLE_AUTH_PROVIDERS_PRIMARY = "AVAILABLE_AUTH_PROVIDERS_PRIMARY"
    const val AVAILABLE_AUTH_PROVIDERS_SECONDARY = "AVAILABLE_AUTH_PROVIDERS_SECONDARY"
    const val MAX_TOTAL_IDENTIFIERS = "MAX_TOTAL_IDENTIFIERS"
    const val MAX_EMAIL_IDENTIFIERS = "MAX_EMAIL_IDENTIFIERS"
    const val MAX_PHONE_IDENTIFIERS = "MAX_PHONE_IDENTIFIERS"
    const val MAX_IDENTIFIERS_PER_EXTERNAL_PROVIDER = "MAX_IDENTIFIERS_PER_EXTERNAL_PROVIDER"
    const val MAX_ACTIVE_SESSIONS_FOR_OPEN_USER = "MAX_ACTIVE_SESSIONS_FOR_OPEN_USER"
    const val MAX_ACTIVE_SESSIONS_FOR_MANAGEMENT_USER = "MAX_ACTIVE_SESSIONS_FOR_MANAGEMENT_USER"
    const val ACCOUNT_DELETION_GRACE_PERIOD_SECONDS = "ACCOUNT_DELETION_GRACE_PERIOD_SECONDS"
    const val ACCOUNT_DELETION_CHECK_INTERVAL_SECONDS = "ACCOUNT_DELETION_CHECK_INTERVAL_SECONDS"
    const val IS_REGISTRATION_ENABLED = "IS_REGISTRATION_ENABLED"
    const val IS_EMAIL_BLACKLIST_ENABLED_OPEN = "IS_EMAIL_BLACKLIST_ENABLED_OPEN"
    const val EMAIL_BLACKLIST_OPEN = "EMAIL_BLACKLIST_OPEN"
    const val IS_EMAIL_WHITELIST_ENABLED_OPEN = "IS_EMAIL_WHITELIST_ENABLED_OPEN"
    const val EMAIL_WHITELIST_OPEN = "EMAIL_WHITELIST_OPEN"
    const val IS_EMAIL_BLACKLIST_ENABLED_MANAGEMENT = "IS_EMAIL_BLACKLIST_ENABLED_MANAGEMENT"
    const val EMAIL_BLACKLIST_MANAGEMENT = "EMAIL_BLACKLIST_MANAGEMENT"
    const val IS_EMAIL_WHITELIST_ENABLED_MANAGEMENT = "IS_EMAIL_WHITELIST_ENABLED_MANAGEMENT"
    const val EMAIL_WHITELIST_MANAGEMENT = "EMAIL_WHITELIST_MANAGEMENT"
    const val GOOGLE_WEB_CLIENT_ID = "GOOGLE_WEB_CLIENT_ID"
    const val UNIONE_API_KEY_FILE = "UNIONE_API_KEY_FILE"
    const val UNIONE_URL = "UNIONE_URL"
    const val UNIONE_FROM_EMAIL = "UNIONE_FROM_EMAIL"
    const val UNIONE_FROM_NAME = "UNIONE_FROM_NAME"
    const val UNIONE_TRACK_DOMAIN = "UNIONE_TRACK_DOMAIN"
    const val UNIONE_API_SEND = "UNIONE_API_SEND"
    const val RESEND_API_KEY_FILE = "RESEND_API_KEY_FILE"
    const val RESEND_URL = "RESEND_URL"
    const val RESEND_FROM_EMAIL = "RESEND_FROM_EMAIL"
    const val RESEND_FROM_NAME = "RESEND_FROM_NAME"
}