package io.github.mudrichenkoevgeny.backend.feature.user.config.envkeys

object UserEnvKeys {
    const val JWT_SECRET_FILE = "JWT_SECRET_FILE"
    const val ACCESS_TOKEN_VALIDITY_HOURS = "ACCESS_TOKEN_VALIDITY_HOURS"
    const val REFRESH_TOKEN_VALIDITY_DAYS = "REFRESH_TOKEN_VALIDITY_DAYS"
    const val AUTH_REALM = "AUTH_REALM"
    const val ADMIN_ACCOUNTS_JSON_SECRET_FILE = "ADMIN_ACCOUNTS_JSON_SECRET_FILE"
    const val AVAILABLE_AUTH_PROVIDERS_PRIMARY = "AVAILABLE_AUTH_PROVIDERS_PRIMARY"
    const val AVAILABLE_AUTH_PROVIDERS_SECONDARY = "AVAILABLE_AUTH_PROVIDERS_SECONDARY"
    const val GOOGLE_WEB_CLIENT_ID = "GOOGLE_WEB_CLIENT_ID"
    const val UNIONE_API_KEY_FILE = "UNIONE_API_KEY_FILE"
    const val UNIONE_URL = "UNIONE_URL"
    const val UNIONE_FROM_EMAIL = "UNIONE_FROM_EMAIL"
    const val UNIONE_FROM_NAME = "UNIONE_FROM_NAME"
    const val UNIONE_TRACK_DOMAIN = "UNIONE_TRACK_DOMAIN"
    const val UNIONE_API_SEND = "UNIONE_API_SEND"
    const val RESEND_API_KEY_FILE = "RESEND_API_KEY_FILE"
    const val RESEND_URL = "RESEND_URL"
    const val RESEND_FROM_EMAIL = "RESEND_FROM_EMAIL"
    const val RESEND_FROM_NAME = "RESEND_FROM_NAME"
}