receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug: {}
  prometheus:
    endpoint: "0.0.0.0:8888"
  otlp/jaeger:
    endpoint: jaeger:4317
    timeout: 10s
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      level: normal
      address: "0.0.0.0:8889"

  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
    logs:
      receivers: [ otlp ]
      exporters: [ debug ]
