package io.github.mudrichenkoevgeny.backend.core.security.config.envkeys

import io.github.mudrichenkoevgeny.backend.core.security.config.factory.SecurityConfigFactoryImpl
import io.github.mudrichenkoevgeny.backend.core.security.config.model.SecurityConfig

/**
 * Environment variable keys used to build [SecurityConfig].
 *
 * These keys are read by [SecurityConfigFactoryImpl]. Consumers typically provide these variables
 * in the host application's deployment configuration.
 */
object SecurityEnvKeys {
    const val AUTH_REALM = "AUTH_REALM"
    const val TOTP_ENCRYPTION_SECRET_FILE = "TOTP_ENCRYPTION_SECRET_FILE"
    const val RECENT_AUTHENTICATION_VALIDITY_IN_SECONDS = "RECENT_AUTHENTICATION_VALIDITY_IN_SECONDS"
    const val RECENT_AUTHENTICATION_VALIDITY_IN_SECONDS_FOR_MANAGEMENT =
        "RECENT_AUTHENTICATION_VALIDITY_IN_SECONDS_FOR_MANAGEMENT"
    const val PASSWORD_POLICY_MIN_LENGTH = "PASSWORD_POLICY_MIN_LENGTH"
    const val PASSWORD_POLICY_REQUIRE_LETTER = "PASSWORD_POLICY_REQUIRE_LETTER"
    const val PASSWORD_POLICY_REQUIRE_UPPER_CASE = "PASSWORD_POLICY_REQUIRE_UPPER_CASE"
    const val PASSWORD_POLICY_REQUIRE_LOWER_CASE = "PASSWORD_POLICY_REQUIRE_LOWER_CASE"
    const val PASSWORD_POLICY_REQUIRE_DIGIT = "PASSWORD_POLICY_REQUIRE_DIGIT"
    const val PASSWORD_POLICY_REQUIRE_SPECIAL_CHAR = "PASSWORD_POLICY_REQUIRE_SPECIAL_CHAR"
    const val PASSWORD_POLICY_COMMON_PASSWORDS = "PASSWORD_POLICY_COMMON_PASSWORDS"
    const val OTP_RETRY_AFTER_SECONDS = "OTP_RETRY_AFTER_SECONDS"
    const val OTP_NUMBER_OF_SYMBOLS = "OTP_NUMBER_OF_SYMBOLS"
    const val OTP_EXPIRATION_SECONDS = "OTP_EXPIRATION_SECONDS"
    const val MFA_TOKEN_EXPIRATION_SECONDS = "MFA_TOKEN_EXPIRATION_SECONDS"
    const val RATE_LIMIT_MAX_REQUESTS_PER_PERIOD = "RATE_LIMIT_MAX_REQUESTS_PER_PERIOD"
    const val RATE_LIMIT_PERIOD_SECONDS = "RATE_LIMIT_PERIOD_SECONDS"
    const val ACCOUNT_LOCKOUT_MAX_FAILED_PASSWORD_ATTEMPTS = "ACCOUNT_LOCKOUT_MAX_FAILED_PASSWORD_ATTEMPTS"
    const val ACCOUNT_LOCKOUT_MAX_FAILED_OTP_ATTEMPTS = "ACCOUNT_LOCKOUT_MAX_FAILED_OTP_ATTEMPTS"
    const val ACCOUNT_LOCKOUT_MAX_FAILED_TOTP_ATTEMPTS = "ACCOUNT_LOCKOUT_MAX_FAILED_TOTP_ATTEMPTS"
    const val ACCOUNT_LOCKOUT_WINDOW_SECONDS = "ACCOUNT_LOCKOUT_WINDOW_SECONDS"
    const val ACCOUNT_LOCKOUT_DURATION_SECONDS = "ACCOUNT_LOCKOUT_DURATION_SECONDS"
    const val ACCOUNT_LOCKOUT_PERMANENT_THRESHOLD = "ACCOUNT_LOCKOUT_PERMANENT_THRESHOLD"
    const val IS_SELF_SERVICE_UNLOCK_ENABLED = "IS_SELF_SERVICE_UNLOCK_ENABLED"
    const val REFRESH_TOKEN_ROTATION_GRACE_PERIOD_SECONDS = "REFRESH_TOKEN_ROTATION_GRACE_PERIOD_SECONDS"

    const val IS_IP_BLACKLIST_ENABLED_OPEN = "IS_IP_BLACKLIST_ENABLED_OPEN"
    const val IP_BLACKLIST_OPEN = "IP_BLACKLIST_OPEN"
    const val IS_IP_WHITELIST_ENABLED_OPEN = "IS_IP_WHITELIST_ENABLED_OPEN"
    const val IP_WHITELIST_OPEN = "IP_WHITELIST_OPEN"

    const val IS_IP_BLACKLIST_ENABLED_MANAGEMENT = "IS_IP_BLACKLIST_ENABLED_MANAGEMENT"
    const val IP_BLACKLIST_MANAGEMENT = "IP_BLACKLIST_MANAGEMENT"
    const val IS_IP_WHITELIST_ENABLED_MANAGEMENT = "IS_IP_WHITELIST_ENABLED_MANAGEMENT"
    const val IP_WHITELIST_MANAGEMENT = "IP_WHITELIST_MANAGEMENT"
}