package io.github.mudrichenkoevgeny.backend.core.security.config.envkeys

object SecurityEnvKeys {
    const val AUTHENTICATION_CONFIRMATION_VALIDITY_MINUTES = "AUTHENTICATION_CONFIRMATION_VALIDITY_MINUTES"
    const val PASSWORD_POLICY_MIN_LENGTH = "PASSWORD_POLICY_MIN_LENGTH"
    const val PASSWORD_POLICY_REQUIRE_LETTER = "PASSWORD_POLICY_REQUIRE_LETTER"
    const val PASSWORD_POLICY_REQUIRE_UPPER_CASE = "PASSWORD_POLICY_REQUIRE_UPPER_CASE"
    const val PASSWORD_POLICY_REQUIRE_LOWER_CASE = "PASSWORD_POLICY_REQUIRE_LOWER_CASE"
    const val PASSWORD_POLICY_REQUIRE_DIGIT = "PASSWORD_POLICY_REQUIRE_DIGIT"
    const val PASSWORD_POLICY_REQUIRE_SPECIAL_CHAR = "PASSWORD_POLICY_REQUIRE_SPECIAL_CHAR"
    const val PASSWORD_POLICY_COMMON_PASSWORDS = "PASSWORD_POLICY_COMMON_PASSWORDS"
}